Working on install script.

diff --git a/install_to_server b/install_to_server
--- a/install_to_server
+++ b/install_to_server
@@ -1,22 +1,30 @@
 #!/bin/bash
 TARGET_DIR=/srv/radico8
-TARGET_USER=radico8
-pushd /etc/systemd/system/
+# TARGET_USER=radico8
 
-echo "Creating the ${TARGET_USER} user..."
-useradd -m -d ${TARGET_DIR} ${TARGET_USER}
-echo
+if [ "${EUID:-$(id -u)}" -ne 0 ]; then
+    echo "Rerun this script as root! Exiting with non-zero error code."
+    exit 1
+fi
 
-git clone 'https://github.com/alanxoc3/radico8.git' "$TARGET_DIR"/repo
+echo "Cloning repo to server location..."
+git clone 'https://github.com/alanxoc3/radico8.git' "$TARGET_DIR"
+
+echo "Installing systemd scripts..."
 
 cat << EOF | tee /etc/systemd/system/radico8.service > /dev/null
 [Unit]
 Description=Headless pico8 instance running radico8.
 
 [Service]
-ExecStart=${TARGET_DIR} ${TARGET_DIR}/repo/start_radio /opt/pico8 ${TARGET_DIR}/repo/cartridges ${TARGET_DIR}/repo/playlist.txt
-WorkingDirectory=${TARGET_DIR}/repo
+ExecStart=${TARGET_DIR} ${TARGET_DIR}/start_radio /opt/pico8 ${TARGET_DIR}/cartridges ${TARGET_DIR}/playlist.txt
+WorkingDirectory=${TARGET_DIR}
 
 [Install]
 WantedBy=multi-user.target
 EOF
+
+echo "Reloading & restarting systemctl..."
+systemctl daemon-reload
+systemctl enable radico8.service
+systemctl start radico8.service
